services:
  postgres:
      image: bitnami/postgresql:latest
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_USER=gus
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=todo_db
      volumes:
        - pg_data:/bitnami/postgresql

volumes:
  pg_data: